##Yaml para CICD Synapse
name: CI222


on:
    push:
      branches:
        - workspace_publish
jobs:
    release:
        # You also can use the self-hosted runners.
        runs-on: windows-latest
        steps:
        # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
        - uses: actions/checkout@v2
        - uses: Azure/Synapse-workspace-deployment@V1.7.0
          with:
            TargetWorkspaceName: ${{secrets.WORKSPACENAME}}
            TemplateFile: './workspacesynapsedev99/TemplateForWorkspace.json'
            ParametersFile: './workspacesynapsedev99/TemplateParametersForWorkspace.json'
            OverrideArmParameters: './workspacesynapsedev99/ParameterPrd.json'
            environment: 'Azure Public'
            resourceGroup: ${{secrets.RESOURCEGROUP}}
            clientId: ${{secrets.CLIENTID}}
            clientSecret:  ${{secrets.CLIENTSECRET}}
            subscriptionId: ${{secrets.SUBSCRIPTIONID}}
            tenantId: ${{secrets.TENANTID}}
            DeleteArtifactsNotInTemplate: 'true'
            managedIdentity: 'False'
            operation: 'deploy'
            
